// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZTpZu5tX4_3ALM273t4Il2LeWN6wzE5Q',
    appId: '1:965131925809:web:f66922577749fff1a31810',
    messagingSenderId: '965131925809',
    projectId: 'jin-walkie',
    authDomain: 'jin-walkie.firebaseapp.com',
    storageBucket: 'jin-walkie.firebasestorage.app',
    measurementId: 'G-299M3PLX72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPVakYr2mGYCmU6RI_DZtOdPTxAX9T1ig',
    appId: '1:965131925809:android:97247b5f334fd7d7a31810',
    messagingSenderId: '965131925809',
    projectId: 'jin-walkie',
    storageBucket: 'jin-walkie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC3IF1AZ9w-EVT1UNBijPUjpxSChOdEzE',
    appId: '1:965131925809:ios:7822cbc46f5242aca31810',
    messagingSenderId: '965131925809',
    projectId: 'jin-walkie',
    storageBucket: 'jin-walkie.firebasestorage.app',
    iosBundleId: 'com.example.jin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC3IF1AZ9w-EVT1UNBijPUjpxSChOdEzE',
    appId: '1:965131925809:ios:7822cbc46f5242aca31810',
    messagingSenderId: '965131925809',
    projectId: 'jin-walkie',
    storageBucket: 'jin-walkie.firebasestorage.app',
    iosBundleId: 'com.example.jin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZTpZu5tX4_3ALM273t4Il2LeWN6wzE5Q',
    appId: '1:965131925809:web:5569600a2f23b625a31810',
    messagingSenderId: '965131925809',
    projectId: 'jin-walkie',
    authDomain: 'jin-walkie.firebaseapp.com',
    storageBucket: 'jin-walkie.firebasestorage.app',
    measurementId: 'G-7D2WE54GBP',
  );
}
